{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gitops-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: gitops-server
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.giantswarm.resources.server.requests.cpu }}
        memory: {{ .Values.giantswarm.resources.server.requests.memory }}
      maxAllowed:
        cpu: 1000m
        memory: 1000mi
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
