version: 2.1
orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push gitops-server chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "gitops-server"
          filters:
            tags:
              only: /^v.*/
